# Generated by Django 2.1.7 on 2024-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
