# Generated by Django 2.1.7 on 2024-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_userprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='static/images/songs_img/')),
                ('audio_file', models.FileField(upload_to='static/audio/')),
            ],
        ),
    ]
